ALTER TABLE posts
DROP
CONSTRAINT fk5lidm6cqbc7u4xhqpxm898qme;

ALTER TABLE comments
DROP
CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq;

ALTER TABLE images
DROP
CONSTRAINT fkcp0pycisii8ub3q4b7x5mfpn1;

ALTER TABLE follower_subscriptions
DROP
CONSTRAINT fkf6ldurpxy3val0wm0hd6k51ng;

ALTER TABLE comments
DROP
CONSTRAINT fkh4c7lvsc298whoyd4w9ta25cr;

ALTER TABLE followers
DROP
CONSTRAINT fkndvqwh40g1qt4xirl6vp2d6m6;

ALTER TABLE likes
DROP
CONSTRAINT fknvx9seeqqyy71bij291pwiwrg;

ALTER TABLE user_info
DROP
CONSTRAINT fkr1b96ca4asuvrhwoqkdmbo7nj;

ALTER TABLE likes
DROP
CONSTRAINT fkry8tnr4x2vwemv2bb0h5hyl0x;

ALTER TABLE follower_subscibers
DROP
CONSTRAINT fkswv5137lbfr837ywuqk4klyhn;

CREATE TABLE card_block_requests
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    card_id       BIGINT                                  NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    reason        VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    processed_at  TIMESTAMP WITHOUT TIME ZONE,
    processed_by  BIGINT,
    admin_comment VARCHAR(255),
    CONSTRAINT pk_card_block_requests PRIMARY KEY (id)
);